language: c++

cache: apt

sudo: false

addons:
  apt:
    packages:
      - libpcap-dev 
      - libusb-1.0-0-dev
      - gcc-4.7
      - g++-4.7

compiler:
  - clang
  - gcc

before_script:
  - mkdir src/build
  - cd src/build
  - CC=gcc-4.7 CXX=g++-4.7 CFLAGS="-g -Wall -Wextra" cmake ..

script: make
